# Dockerfile
# 
# Configuration Docker pour l'environnement de développement PHP/Apache
# 
# Commentaire spécifique: Fichier de configuration pour le projet App-Soutenance
# 
# @author ManuelD-Aho
# @created 2025-04-21 16:18:23

# Contenu ici

