version: '3.8'

services:
  # Service PHP/Apache pour l'application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-soutenance-dev
    volumes:
      # Montage du code source pour le développement en temps réel
      - .:/var/www/html
      # Configuration PHP personnalisée
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8080:80"
    environment:
      - APP_ENV=development
      - PHP_IDE_CONFIG=serverName=app-soutenance
      # variables d'environnement PHP chargées depuis .env
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # Mode développement
      - APP_DEBUG=true
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  # Service MySQL pour la base de données
  db:
    image: mysql:8.3
    container_name: app-soutenance-db-dev
    volumes:
      - db-data:/var/lib/mysql
      # Initialisation de la base de données avec le fichier SQL existant
      - ./soutenance.sql:/docker-entrypoint-initdb.d/soutenance.sql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # Port exposé uniquement en développement
      - "3306:3306"
    networks:
      - app-network
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Service phpMyAdmin pour la gestion de la base de données - Accès avec root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: app-soutenance-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 64M
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local