# Dockerfile
# 
# Configuration Docker optimisée pour la production avec multi-stage build
# 
# Commentaire spécifique: Fichier de configuration pour le projet App-Soutenance
# 
# @author ManuelD-Aho
# @created 2025-04-21 16:18:23

# Contenu ici

